name: Pipeline to AWS S3

on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    name: CI/CD pipeline
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone
      uses: actions/checkout@v1

    - name: Get AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
        aws-region            : ${{ secrets.AWS_REGION_NAME }}

    - name: Sync to AWS S3
      run: |
        aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }} \
        --delete \
        --exclude ".git/*" \
        --exclude ".github/*"

    - name: Success log msg
      run: echo "Successfully deployed to AWS S3 Bucket"

  
